### ISSUE TITLE
Code and assets stolen from RAA

### ISSUE THREAD

**Issue by oliviathevampire** [anatom3000/GuessWhatWillHappenInThis#95]
Hi! I just found this and while looking through the code and textures I've seen a lot taken from my team's Randomly Adding Anything mod and I do not appreciate that. I would like it to be removed asap.

**Comment by Ryorama** [comment]
Hey! I don’t really work on this mod much anymore, but I can bring this up to the owners in the mods discord server. I was looking through recent commits and I found this and wanted to ask if this is what you where referencing https://github.com/anatom3000/GuessWhatWillHappenInThis/commit/9171afa607f5660ac0c199b2acadf60e6f261eb2#diff-922db1578bde7e3ba01cc4d33c27247ad27bbb25296ad2468644f97cb288a885? Thanks for bringing this up and I hope you have a great day/night!

**Comment by ENDERZOMBI102** [comment]
what textures exactly?

**Comment by oliviathevampire** [comment]
> what textures exactly?

@ENDERZOMBI102 most of the ore and ore block textures. And I also think some of the tool textures.

**Comment by oliviathevampire** [comment]
> Hey! I don’t really work on this mod much anymore, but I can bring this up to the owners in the mods discord server. I was looking through recent commits and I found this and wanted to ask if this is what you where referencing [9171afa#diff-922db1578bde7e3ba01cc4d33c27247ad27bbb25296ad2468644f97cb288a885](https://github.com/anatom3000/GuessWhatWillHappenInThis/commit/9171afa607f5660ac0c199b2acadf60e6f261eb2#diff-922db1578bde7e3ba01cc4d33c27247ad27bbb25296ad2468644f97cb288a885)? Thanks for bringing this up and I hope you have a great day/night!

Are you thinking of the RAA discord or the discord for this mod?

**Comment by Ryorama** [comment]
> > Hey! I don’t really work on this mod much anymore, but I can bring this up to the owners in the mods discord server. I was looking through recent commits and I found this and wanted to ask if this is what you where referencing [9171afa#diff-922db1578bde7e3ba01cc4d33c27247ad27bbb25296ad2468644f97cb288a885](https://github.com/anatom3000/GuessWhatWillHappenInThis/commit/9171afa607f5660ac0c199b2acadf60e6f261eb2#diff-922db1578bde7e3ba01cc4d33c27247ad27bbb25296ad2468644f97cb288a885)? Thanks for bringing this up and I hope you have a great day/night!
> 
> Are you thinking of the RAA discord or the discord for this mod?

Sorry, I meant the one for this mod.

**Comment by oliviathevampire** [comment]
> > > Hey! I don’t really work on this mod much anymore, but I can bring this up to the owners in the mods discord server. I was looking through recent commits and I found this and wanted to ask if this is what you where referencing [9171afa#diff-922db1578bde7e3ba01cc4d33c27247ad27bbb25296ad2468644f97cb288a885](https://github.com/anatom3000/GuessWhatWillHappenInThis/commit/9171afa607f5660ac0c199b2acadf60e6f261eb2#diff-922db1578bde7e3ba01cc4d33c27247ad27bbb25296ad2468644f97cb288a885)? Thanks for bringing this up and I hope you have a great day/night!
> > 
> > 
> > Are you thinking of the RAA discord or the discord for this mod?
> 
> Sorry, I meant the one for this mod.

Do you have an invite link?

**Comment by Ryorama** [comment]
> > > > Hey! I don’t really work on this mod much anymore, but I can bring this up to the owners in the mods discord server. I was looking through recent commits and I found this and wanted to ask if this is what you where referencing [9171afa#diff-922db1578bde7e3ba01cc4d33c27247ad27bbb25296ad2468644f97cb288a885](https://github.com/anatom3000/GuessWhatWillHappenInThis/commit/9171afa607f5660ac0c199b2acadf60e6f261eb2#diff-922db1578bde7e3ba01cc4d33c27247ad27bbb25296ad2468644f97cb288a885)? Thanks for bringing this up and I hope you have a great day/night!
> > > 
> > > 
> > > Are you thinking of the RAA discord or the discord for this mod?
> > 
> > 
> > Sorry, I meant the one for this mod.
> 
> Do you have an invite link?

https://discord.gg/d7pvgQypHC

**Comment by lnee94** [comment]
how does this violate the cc0 license or the mit license

**Comment by ENDERZOMBI102** [comment]
cc0 expects retribution and other stuff iirc

**Comment by oliviathevampire** [comment]
> how does this violate the cc0 license or the mit license

There is not even any credit to RAA or anything, it’s like they just said “I like this lemme just yoink it and put it into this mod”

**Comment by ENDERZOMBI102** [comment]
@oliviathevampire how's the pr going? if you're even working on it

**Comment by JFronny** [comment]
If i am correct, reverting https://github.com/anatom3000/GuessWhatWillHappenInThis/commit/9171afa607f5660ac0c199b2acadf60e6f261eb2 (which only has one conflict in TextureBuilder, where the code from that commit was later improved, but that can be reverted) should do the trick as I didn't take any graphics from other mods for my original impl

**Comment by oliviathevampire** [comment]
> @oliviathevampire how's the pr going? if you're even working on it next week i have some time, if you don't pr i'll do it, so no worries : )

sadly not had time @ENDERZOMBI102

**Comment by ENDERZOMBI102** [comment]
@oliviathevampire its ok, i can do it

**Comment by ENDERZOMBI102** [comment]
commit reminder:
- textures:
    - 9171afa
