### ISSUE TITLE
Hyperspeed Pill

### ISSUE THREAD

**Issue by UniqueName12345** [anatom3000/GuessWhatWillHappenInThis#98]
The hyperspeed pill will make you go superfast, but it will only last for 10 seconds.

**Comment by anatom3000** [comment]
I'm not sure if this is too OP or not enough OP for this mod

**Comment by UniqueName12345** [comment]
> I'm not sure if this is too OP or not enough OP for this mod

It shouldn't be too op, as it is going be like a 7x speed change.
